// Generated by Wrangler on Sun May 26 2024 14:27:41 GMT+0300 (Eastern European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DB: D1Database;
}
